version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_server
    environment:
      MYSQL_ROOT_PASSWORD: ${SURVEY_DB_ROOT}
      MYSQL_DATABASE: survey
      MYSQL_USER: ${SURVEY_DB_USER}
      MYSQL_PASSWORD: ${SURVEY_DB_PASS}        
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    volumes:
      - ./mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    env_file:
      - .env
    networks:
      - app_network      

  surveymanager_app:
    image: resoto/surveymanager:0.0
    container_name: surveymanager_app
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/survey
      SPRING_DATASOURCE_USERNAME: ${SURVEY_DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${SURVEY_DB_PASS}
      OKTA_OAUTH2_ISSUER: ${OAUTH_ISSUER}
      OKTA_OAUTH2_CLIENT-ID: ${SURVEYMANAGER_OAUTH_CLIENT}
      OKTA_OAUTH2_CLIENT-SECRET: ${SURVEYMANAGER_OAUTH_SECRET}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/healthcheck"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    ports:
      - "8081:8081"
    depends_on:
      mysql:
        condition: service_healthy
    env_file:
      - .env
    networks:
      - app_network

  surveyhandler_app:
    image: resoto/surveyhandler:0.0
    container_name: surveyhandler_app
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/survey
      SPRING_DATASOURCE_USERNAME: ${SURVEY_DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${SURVEY_DB_PASS}
      OKTA_OAUTH2_ISSUER: ${OAUTH_ISSUER}
      OKTA_OAUTH2_CLIENT-ID: ${SURVEYHANDLER_OAUTH_CLIENT}
      OKTA_OAUTH2_CLIENT-SECRET: ${SURVEYHANDLER_OAUTH_SECRET}
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      mysql:
        condition: service_healthy
      surveymanager_app:
        condition: service_started
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
